import { useQuery } from '@apollo/client/react';
import { GetUsersDocument } from '@/api/generated/graphql';
import type { GetUsersQuery } from '@/api/generated/graphql';

// useUsers — fetches the full user list from the API via GraphQL.
//
// This hook is the only entry point components have to this data.
// Components must never call useQuery directly.
//
// The query document (GetUsersDocument) and all types (GetUsersQuery) are
// auto-generated by graphql-codegen from:
//   src/api/operations/users/getUsers.query.graphql
// Run `npm run codegen` (with the API running) to regenerate after schema changes.
//
// Internally:
//   useQuery sends POST /graphql with the GetUsers operation
//   → Vite proxy forwards to localhost:3001/graphql
//   → Apollo Server resolves Query.users → UserService → UserRepository → PostgreSQL
//   → Apollo Client stores the result in InMemoryCache and re-renders the component
//
// Returns:
//   users   — User[] (empty array while loading or on error)
//   loading — true while the request is in flight
//   error   — ApolloError if the request failed, undefined otherwise
export const useUsers = () => {
  const { data, loading, error } = useQuery<GetUsersQuery>(GetUsersDocument);

  return {
    users: data?.users ?? ([] as GetUsersQuery['users']),
    loading,
    error,
  };
};
